FROM node

RUN mkdir /backend
COPY backend/package.json backend/package.json

WORKDIR /backend
RUN npm install & \
    npm install -g nodemon

VOLUME [ "/backend" ]
ARG PORT
EXPOSE $PORT
ENTRYPOINT [ "npm", "run", "start" ]